site_name: Knowledge Base
theme: 
  name: material
  language: de
  features:
    #- toc.integrate
    - search.suggest
    - content.tabs.link
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.tracking
    #- navigation.sections
  palette:
    - scheme: slate
      primary: orange
      accent: orange
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed


