site_name: Knowledge Base
theme: 
  name: material
  language: de
  features:
    #- toc.integrate
    - search.suggest
    - content.tabs.link
    #- search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.expand
    - navigation.tracking
    #- navigation.sections
    - content.footnote.tooltips
  palette:
      scheme: slate
      primary: orange
      accent: orange
  

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - footnotes
  - toc:
      toc_depth: 2

site_url: https://mavzlais.github.io/knowledge-base

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mavzlais/knowledge-base

copyright: 'This work is licensed under the <a href="https://mit-license.org/">MIT License</a>.'

repo_url: https://github.com/mavzlais/knowledge-base
repo_name: mavzlais/knowledge-base

nav:
  - Willkommen: index.md 
  
  - Wiki AP2:
    - Inhalt: 02_wiki_ap2/index.md
    - Konzeption und Administration:
      - Inhalt: 02_wiki_ap2/1_konzeption_und_administration_von_it-systemen/index.md
      #- Kommunikation: 02_wiki_ap2/1_konzeption_und_administration_von_it-systemen/01_kommunikation.md
      #- Kundenbeziehungen: 02_wiki_ap2/1_konzeption_und_administration_von_it-systemen/02_kundenbeziehungen.md