site_name: Knowledge Base
theme: 
  name: material
  language: de
  features:
    #- toc.integrate
    - search.suggest
    - content.tabs.link
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.expand
    - navigation.tracking
    #- navigation.sections
    - content.footnote.tooltips
  toc:
    depth: 2
  palette:
    - scheme: slate
      primary: orange
      accent: orange
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - footnotes


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mavzlais/knowledge-base
copyright: 'This work is licensed under the <a href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3</a>.'